version: '3.8'

services:
  tr808-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tr808-drum-machine
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source for development
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.tr808.service=drum-machine"
      - "com.tr808.environment=development"

  # Monitoring stack (optional for local development)
  prometheus:
    image: prom/prometheus:latest
    container_name: tr808-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: tr808-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    profiles:
      - monitoring

volumes:
  grafana-data:

networks:
  default:
    name: tr808-network